Longer timeout
Because still getting erros in QA:
2016-09-13T01:56:13.435+03 ERROR {}
[hakurekisteri-akka.actor.default-dispatcher-3539] ERROR
fi.vm.sade.hakurekisteri.web.rekisteritiedot.RekisteritiedotResource:
incident 02e4f305-0128-401f-a6ae-4cc49c14cfde
akka.pattern.AskTimeoutException: Ask timed out on
[Actor[akka://hakurekisteri/user/arvosanat#500909851]] after [300000
ms].
Sender[Actor[akka://hakurekisteri/user/arvosana-authorizer#947736763]]
sent message of type "fi.vm.sade.hakurekisteri.arvosana.ArvosanatQuery".