Increase timeout values in test
This sometimes seems to fail because of
slowness on Travis:

- should be usable from multiple actor systems *** FAILED ***
  java.util.concurrent.TimeoutException: Futures timed out after [1 second]
...
2019-01-09T22:44:13.775+02  INFO CacheFactory$RedisCacheFactory$RedisCache:202 - Checking contains fi.vm.sade.hakurekisteri.integration.RedisCacheSpec:prefix3:foo from Redis took 1995 ms