SEC-68 : Configurable Sure db thread count
It needs to be configured to a compatible value with
max connections in Slick 3:

java.lang.IllegalArgumentException: requirement failed: When using queueSize > 0, maxThreads <= maxConnections is required.