Even longer timeouts for arvosana and rekisteritiedot queries
because got timeouts in qa:
2016-09-11T01:58:35.067+03 ERROR {}
[hakurekisteri-akka.actor.default-dispatcher-17706] ERROR
fi.vm.sade.hakurekisteri.web.rekisteritiedot.RekisteritiedotResource:
incident 514f709c-31ac-46ea-8af0-27a2f9dbff89
akka.pattern.AskTimeoutException: Ask timed out on
[Actor[akka://hakurekisteri/user/arvosanat#529061157]] after [300000
ms].
Sender[Actor[akka://hakurekisteri/user/arvosana-authorizer#1342072745]]
sent message of type "fi.vm.sade.hakurekisteri.arvosana.ArvosanatQuery".
	at
akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at
scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at
scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)

2016-09-11T01:59:47.431+03 INFO  {}
[hakurekisteri-akka.actor.default-dispatcher-17713] INFO
fi.vm.sade.hakurekisteri.arvosana.ArvosanaJDBCActor: Query select
"resource_id", "inserted", "deleted", "current", "suoritus", "arvosana",
"asteikko", "aine", "lisatieto", "valinnainen", "pisteet", "myonnetty",
"source", "lahde_arvot", "jarjestys" from "arvosana" where ("current"
and ("deleted" = false)) and ("suoritus" in
('b57e1882-6c6a-4ba3-9cb1-0c69e4e9e244',
'06db1aec-0a48-4d8b-9365-120591a9520c',
'1d6f7328-f489-42d4-8857-20bb8d60f02f',
'5a485fbb-1615-4ac8-a052-170383574f70',
'a627b978-c11d-4540-8666-ebd421103946',
'9b3f48e1-e9d6-4d98-a344-a3f25d31...(truncated from 173947 chars) took
632713 ms