Longer timout for getAll
because got timeout erros on QA:
2016-09-11T02:30:36.561+03 ERROR {}
[hakurekisteri-akka.actor.default-dispatcher-17904] ERROR
fi.vm.sade.hakurekisteri.web.rekisteritiedot.RekisteritiedotResource:
incident 33c899f5-a17a-49e1-861a-4c399459f28e
java.util.concurrent.TimeoutException: Futures timed out after [10
seconds]
	at
scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at
scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at
scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at
scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at
fi.vm.sade.hakurekisteri.rest.support.JDBCRepository$class.getAll(JDBCRepository.scala:34)
	at
fi.vm.sade.hakurekisteri.suoritus.SuoritusJDBCActor.getAll(SuoritusJDBCActor.scala:20)