Increase db conn timeout in test
This sometimes seems to fail because of
slowness on Travis:

2019-01-10T10:16:55.622+02  INFO HikariDataSource:70 - suoritusrekisteri.db - Started.
2019-01-10T10:16:57.071+02 ERROR ScalatraListener:137 - Failed to initialize scalatra application at /suoritusrekisteri
java.sql.SQLTransientConnectionException: suoritusrekisteri.db - Connection is not available, request timed out after 1416ms.

While we're at it, also make the db connection timeout
configurable in production config.